/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.45
 * Generated at: 2019-10-30 06:48:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import LF.member.model.vo.*;

public final class MainPag_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/views/member/../common/menubar.jsp", Long.valueOf(1572413193263L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("LF.member.model.vo");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write(".headbanner{\r\n");
      out.write("\twidth:100%;\r\n");
      out.write("\tmin-width:1100px;\r\n");
      out.write("\theight:700px;\r\n");
      out.write("\tbackground:lightgray;\r\n");
      out.write("\tmargin-top:110px;\r\n");
      out.write("\tmargin-bottom:0;\r\n");
      out.write("\tpadding:0px;\r\n");
      out.write("\tbackground:url('");
      out.print(request.getContextPath());
      out.write("/images/banner.jpg') no-repeat;\r\n");
      out.write("\tbackground-size: cover; \r\n");
      out.write("\tbackground-repeat: no-repeat; \r\n");
      out.write("\tbackground-position: center;\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("\topacity:0.8;\r\n");
      out.write("}\r\n");
      out.write("#slideDiv{\r\n");
      out.write("\tdisplay:inline-block;\r\n");
      out.write("\tmin-width:900px;\r\n");
      out.write("\twidth:500px;\r\n");
      out.write("\theight:450px;\r\n");
      out.write("\tbackground:white;\r\n");
      out.write("\tmargin-top:250px;\r\n");
      out.write("}\r\n");
      out.write("#vertical img{\r\n");
      out.write("\twidth:750px;\r\n");
      out.write("\theight:440px;\r\n");
      out.write("\tmargin:0;\r\n");
      out.write("\tpadding:0;\r\n");
      out.write("}\r\n");
      out.write(".secondMainDiv{\r\n");
      out.write("\theight:100%;\r\n");
      out.write("\tmargin-top:20px;\r\n");
      out.write("\tmin-width:1100px;\r\n");
      out.write("\tmin-height:1000px;\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("}\r\n");
      out.write("#newProduct{\r\n");
      out.write("\tdisplay:inline-block;\r\n");
      out.write("\twidth:1200px;\r\n");
      out.write("\theight:620px;\r\n");
      out.write("\tborder:1px solid black;\r\n");
      out.write("}\r\n");
      out.write("#reviewSlide{\r\n");
      out.write("\tdisplay:inline-block;\r\n");
      out.write("\tmargin-top:10px;\r\n");
      out.write("\tmargin-bottom:10px;\r\n");
      out.write("\twidth:900px;\r\n");
      out.write("\theight:500px;\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("\tpadding:20px;\r\n");
      out.write("\tborder: 1px solid black;\r\n");
      out.write("\tborder-radius: 3%;\r\n");
      out.write("}\r\n");
      out.write(".card.cardSize{\r\n");
      out.write("\twidth:250px;\r\n");
      out.write("\theight:400px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write('\r');
      out.write('\n');

	Customer loginUser = (Customer)session.getAttribute("loginUser");
	Seller sellerUser = (Seller)session.getAttribute("sellerUser");
	Admin adminUser = (Admin)session.getAttribute("adminUser");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\"> \r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"  href=\"https://cdnjs.cloudflare.com/ajax/libs/lightslider/1.1.6/css/lightslider.min.css\"/>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"http://dmaps.daum.net/map_js_init/postcode.v2.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/lightslider/1.1.6/js/lightslider.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t.headerNavi{\t\r\n");
      out.write("\t\tdisplay:inline-block;\r\n");
      out.write("\t\tborder-radius:5px;\r\n");
      out.write("\t\twidth:auto;\r\n");
      out.write("\t\theight:auto;\r\n");
      out.write("\t}\r\n");
      out.write("\t.genric-btn {\r\n");
      out.write("  \t\tdisplay: inline-block;\r\n");
      out.write("  \t\toutline: none;\r\n");
      out.write("  \t\tline-height: 40px;\r\n");
      out.write("  \t\tpadding: 0 30px;\r\n");
      out.write("  \t\tfont-size: .8em;\r\n");
      out.write("  \t\ttext-align: center;\r\n");
      out.write("  \t\ttext-decoration: none;\r\n");
      out.write("  \t\tfont-weight: 500;\r\n");
      out.write("  \t\tcursor: pointer;\r\n");
      out.write("  \t\t-webkit-transition: all 0.3s ease 0s;\r\n");
      out.write("  \t\t-moz-transition: all 0.3s ease 0s;\r\n");
      out.write("  \t\t-o-transition: all 0.3s ease 0s;\r\n");
      out.write("  \t\ttransition: all 0.3s ease 0s;\r\n");
      out.write("\t}\r\n");
      out.write("\t.genric-btn.radius {\r\n");
      out.write(" \t\tborder-radius: 3px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.genric-btn.medium {\r\n");
      out.write("  \t\tline-height: 30px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.genric-btn.info {\r\n");
      out.write("  \t\tcolor: #fff;\r\n");
      out.write("  \t\tbackground: #38a4ff;\r\n");
      out.write("  \t\tborder: 1px solid transparent;\r\n");
      out.write("\t}\r\n");
      out.write("\t.genric-btn.circle {\r\n");
      out.write("  \t\tborder-radius: 20px;\r\n");
      out.write("\t}\r\n");
      out.write("\t#menuBtn{\r\n");
      out.write("\t\tbackground:url('");
      out.print(request.getContextPath());
      out.write("/images/menubtn.png') no-repeat;\r\n");
      out.write("\t\tbackground-size: 80%; \r\n");
      out.write("\t\tbackground-repeat: no-repeat; \r\n");
      out.write("\t\tbackground-position: center;\r\n");
      out.write("\t\tborder: 0px;\r\n");
      out.write("\t\theight: 75px;\r\n");
      out.write("\t\twidth : 75px;\r\n");
      out.write("\t}\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t#inlineUl li{\r\n");
      out.write("\t\tdisplay:inline;\r\n");
      out.write("\t}\r\n");
      out.write("\t#rightMenu{\r\n");
      out.write("\t\talign:right;\r\n");
      out.write("\t}\r\n");
      out.write("\t#menu{\r\n");
      out.write("\t\twidth: 250px; \r\n");
      out.write("\t\theight:calc(100% - 110px); \r\n");
      out.write("\t\tposition: fixed; \r\n");
      out.write("\t\ttop: 110px; \r\n");
      out.write("\t\tleft: -320px; \r\n");
      out.write("\t\tz-index: 1055;\r\n");
      out.write("\t\tbackground-color: #eee; \r\n");
      out.write("\t\tfont-size:1.2em;\r\n");
      out.write("\t\ttransition: All 0.2s ease;\r\n");
      out.write("\t\toverflow-x:hidden;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#menu.open{\r\n");
      out.write("\t\tleft:0px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.material-icons.md-25{\r\n");
      out.write("\t\tcolor:black;\r\n");
      out.write("\t\tfont-size:25px;\r\n");
      out.write("\t\tvertical-align:bottom;\r\n");
      out.write("\t}\r\n");
      out.write("\t.linkSpan{\r\n");
      out.write("\t\tposition: relative;\r\n");
      out.write("\t    top: 1px;\r\n");
      out.write("\t    display: inline-block;\r\n");
      out.write("\t    font-style: normal;\r\n");
      out.write("   \t\tfont-weight: 400;\r\n");
      out.write("\t    line-height: 1;\r\n");
      out.write("\t}\r\n");
      out.write("\t.linkC{\r\n");
      out.write("\t\tpadding: 12px 8px 12px 16px;\r\n");
      out.write("\t    font-size: 1.1em;\r\n");
      out.write("\t    text-decoration:none;\r\n");
      out.write("\t    color: #333;\r\n");
      out.write("\t\tdisplay: block;\r\n");
      out.write("\t    transition: .3s;\r\n");
      out.write("\t}\r\n");
      out.write("\t.aline{\r\n");
      out.write("\t\tborder-bottom: 1px solid #444;\r\n");
      out.write("\t}\r\n");
      out.write("\t.table-borderless td{\r\n");
      out.write("\t\tmargin-top:5px;\r\n");
      out.write("\t\tmargin-bottom:5px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.modal-body td{\r\n");
      out.write("\t\ttext-align:left;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- header역할을 하며 로그인, 회원가입, 메뉴바를 열수 있는 버튼을 생성 -->\r\n");
      out.write("\t<div class=\"navbar navbar-expand-sm bg-light navbar-dark fixed-top row\" id=\"headerDiv\"style=\"min-width: 1200px; z-index:1055; float:top;\" >\r\n");
      out.write("\t\t<div class=\"headerNavi col-sm-1\" align=\"left\" >\r\n");
      out.write("\t\t\t<input id=\"menuBtn\" type=\"button\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"headerNavi col-sm-8\" align=\"center\">\r\n");
      out.write("\t\t\t<img id=\"logo\" src=\"");
      out.print(request.getContextPath());
      out.write("/images/logo.png\" height='75' width=\"300\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"headerNavi col-sm-3\" id=\"rightMenu\" style=\"min-width:500px;\">\r\n");
      out.write("\t\t\t");
 if(loginUser == null) {
      out.write("\r\n");
      out.write("\t\t\t\t<ul id=\"inlineUl\">\r\n");
      out.write("\t\t\t\t\t<li><button id=\"loginBtn\" class=\"genric-btn info circle\" type=\"button\" style=\"align:right;\" data-toggle=\"modal\" data-target=\"#loginModal\">로그인</button></li>\r\n");
      out.write("\t\t\t\t\t<li><button id=\"signUpBtn\" class=\"genric-btn info circle\" type=\"button\" style=\"align:right;\" data-toggle=\"modal\" data-target=\"#signupModal\">회원가입</button></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t");
} else { 
      out.write("\r\n");
      out.write("\t\t\t\t<ul id=\"inlineUl\">\r\n");
      out.write("\t\t\t\t\t<li style=\"display:inline-block; vertical-align:middle\">");
      out.print(loginUser.getUserName() );
      out.write("님 환영합니다.</li>\r\n");
      out.write("\t\t\t\t\t<li><button id=\"logoutBtn\" class=\"genric-btn info circle\" type=\"button\" style=\"align:right;\">로그아웃</button></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 슬라이드 형식으로 버튼 클릭시 도출되는 메뉴바 -->\r\n");
      out.write("\t<div id=\"menu\">\r\n");
      out.write("\t\t<a href=\"views/Main/MainPage.jsp\" class=\"linkC\"><span class=\"linkSpan\"><i class=\"material-icons md-25\">home</i></span>&nbsp;&nbsp;Home</a>\r\n");
      out.write("\t\t");
 if(loginUser == null) {
      out.write("\r\n");
      out.write("\t\t<a href=\"#loginBtn\" class=\"linkC aline\"><span class=\"linkSpan\"><i class=\"material-icons md-25\">account_circle</i></span>&nbsp;&nbsp;My Page</a>\r\n");
      out.write("\t\t");
} else if(loginUser.getGroupNum().equals("1")) {
      out.write("\r\n");
      out.write("\t\t<a href=\"#\" class=\"linkC aline\"><span class=\"linkSpan\"><i class=\"material-icons md-25\">account_circle</i></span>&nbsp;&nbsp;My Page</a>\r\n");
      out.write("\t\t");
} else if(loginUser.getGroupNum().equals("2")) {
      out.write("\r\n");
      out.write("\t\t<a href=\"#\" class=\"linkC aline\"><span class=\"linkSpan\"><i class=\"material-icons md-25\">account_circle</i></span>&nbsp;&nbsp;My Page</a>\r\n");
      out.write("\t\t");
} else if(loginUser.getGroupNum().equals("3")){
      out.write("\r\n");
      out.write("\t\t<a href=\"");
      out.print(request.getContextPath() );
      out.write("/cuInfo.ad?currentPage=1\" class=\"linkC aline\"><span class=\"linkSpan\"><i class=\"material-icons md-25\">account_circle</i></span>&nbsp;&nbsp;Admin Page</a>\r\n");
      out.write("\t\t");
}
      out.write("\r\n");
      out.write("\t\t<a href=\"#\" class=\"linkC\"><span class=\"linkSpan\"><i class=\"material-icons md-25\">add_shopping_cart</i></span>&nbsp;&nbsp;상품 게시판</a>\r\n");
      out.write("\t\t<a href=\"#\" class=\"linkC aline\"><span class=\"linkSpan\"><i class=\"material-icons md-25\">shopping_basket</i></span>&nbsp;&nbsp;장바구니</a>\r\n");
      out.write("\t\t<a hr1ef=\"#\" class=\"linkC\"><span class=\"linkSpan\"><i class=\"material-icons md-25\">shopping_cart</i></span>&nbsp;&nbsp;HOME</a>\r\n");
      out.write("\t\t<a href=\"#\" class=\"linkC\"><span class=\"linkSpan\"><i class=\"material-icons md-25\">https</i></span>&nbsp;&nbsp;HOME</a>\r\n");
      out.write("\t\t<a href=\"#\" class=\"linkC\"><span class=\"linkSpan\"><i class=\"material-icons md-25\">question_answer</i></span>&nbsp;&nbsp;고객센터</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t");
 if(loginUser == null) {
      out.write("\r\n");
      out.write("\t<div class=\"modal fade\" id=\"loginModal\" tabindex=\"-1\" role=\"dialog\">\r\n");
      out.write("\t\t<form id=\"loginForm\" action=\"");
      out.print(request.getContextPath());
      out.write("/login.me\" onsubmit=\"return loginValidate();\" method=\"post\">\r\n");
      out.write("\t\t<div class=\"modal-dialog modal-dialog-centered\" style=\"width: 400px;\">\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Modal Header -->\r\n");
      out.write("\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t<h4 class=\"modal-title\">로그인</h4>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Modal body -->\r\n");
      out.write("\t\t\t\t<div class=\"modal-body\" style=\"padding: 30px; text-align:center;\">\r\n");
      out.write("\t\t\t\t\t<!-- <form id=\"loginInfo\"> -->\r\n");
      out.write("\t\t\t\t\t\t<table class=\"table-borderless\" style=\"display:inline-block\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>아이디</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" class=\"form-control\" id=\"loginId\" name=\"loginId\" required></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>비밀번호</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"password\" class=\"form-control\" id=\"loginPwd\" name=\"loginPwd\" required></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=2 align=\"right\"><a href=\"#\">아이디/비밀번호 찾기</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("<!-- \t\t\t\t\t</form> -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Modal footer -->\r\n");
      out.write("\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t<button id=\"loginConnect\" type=\"submit\" class=\"btn btn-success\">로그인</button>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-success\" data-dismiss=\"modal\" id=\"closeLogin\">닫기</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
} 
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 회원가입 모달 -->\r\n");
      out.write("\t");
 if(loginUser == null) {
      out.write("\r\n");
      out.write("\t<div class=\"modal fade\" id=\"signupModal\" tabindex=\"-1\" role=\"dialog\" style=\"margin-top:30px;\">\r\n");
      out.write("\t\t<form id=\"signupForm\" action=\"");
      out.print(request.getContextPath());
      out.write("/signup.me\" onsubmit=\"return signValidate();\" method=\"post\">\r\n");
      out.write("\t\t<div class=\"modal-dialog modal-dialog-centered modal-lg\">\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Modal Header -->\r\n");
      out.write("\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t<h4 class=\"modal-title\" >회원가입</h4>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"close\" id=\"closeSignup\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Modal body -->\r\n");
      out.write("\t\t\t\t<div class=\"modal-body\" style=\"padding: 10px; text-align:center;\">\r\n");
      out.write("\t\t\t\t\t\t<table class=\"table-borderless\"  style=\"display:inline-block;\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>아이디</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" class=\"form-control\" id=\"signupId\" name=\"signupId\" required></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td style=\"width:10px;\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><button type=\"button\" onclick=\"idCheck();\">중복체크</button></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"100px\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>비밀번호</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"password\" class=\"form-control\" id=\"signupPwd\" name=\"signupPwd\" required></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>비밀번호 재확인&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"password\" class=\"form-control\" id=\"signupPwd2\" name=\"signupPwd2\" required></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=2 style=\"font-size:11px; vertical-align:bottom;\"><p style=\"margin-top:10px;\" id=\"matchingPwd\"></p></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>이름</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" class=\"form-control\" id=\"userName\" name=\"userName\" required></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>주소</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" class=\"form-control\" id=\"address1\" name=\"address1\" placeholder=\"우편번호\" readonly></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><button type=\"button\" onclick=\"addressFind()\">주소 검색</button>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=4><input type=\"text\" class=\"form-control\" id=\"address2\" name=\"address2\" placeholder=\"주소\" required></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=4><input type=\"text\" class=\"form-control\" id=\"address3\" name=\"address3\" placeholder=\"상세주소\" required></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>휴대전화</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" class=\"form-control\" id=\"phoneNum\" name=\"phoneNum\" required></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>이메일</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" class=\"form-control\" id=\"emailAddress\" name=\"emailAddress\" required></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>@</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <td id=\"hiddenEmail\"></td> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<td style=\"display:inline-block\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select name=\"emailLog\" id=\"emailLog\" class=\"custom-select\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"\" selected>-- 선택 --</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"naver.com\">naver.com</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"hanmail.net\">hanmail.net</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"gmail.com\">gmail.com</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Modal footer -->\r\n");
      out.write("\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t<button id=\"signupConnect\" type=\"submit\" class=\"btn btn-success\">가입</button>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-success\" data-dismiss=\"modal\" id=\"closeSign\">닫기</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\t$(\"#signupId\").focus();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t/* 메뉴바 버튼 */\r\n");
      out.write("\t\t\t$(\"#menuBtn\").click(function() {\r\n");
      out.write("\t\t\t\tif ($(\"#menu\").hasClass(\"open\")) { //class에 open이 없을 시 open클래스 추가 있을 시 삭제\r\n");
      out.write("\t\t\t\t\t$(\"#menu\").removeClass(\"open\");\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$(\"#menu\").addClass(\"open\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t// 일반회원 버튼\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 판매자 버튼\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 관리자 버튼\r\n");
      out.write("\t\t\t$(\"#adminPage\").click(function(){\r\n");
      out.write("\t\t\t\tlocation.href=\"../admin/adminMainPage.jsp\"\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t/* 로그인 기능 */\r\n");
      out.write("\t\t\t// validate() 함수 작성하기(form태그가 submit되었을 때 실행 됨)\r\n");
      out.write("\t\t\tfunction loginValidate(){\r\n");
      out.write("\t\t\t\tif($(\"#userId\").val().trim().length==0){\r\n");
      out.write("\t\t\t\t\talert(\"아이디를 입력하세요\");\r\n");
      out.write("\t\t\t\t\t$(\"#userId\").focus();\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\treturn false;\t// return값이 false면 submit이 되지 않는다.\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif($(\"#userPwd\").val().trim().length==0){\r\n");
      out.write("\t\t\t\t\talert(\"비밀번호를 입력하세요\");\r\n");
      out.write("\t\t\t\t\t$(\"#userPwd\").focus();\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\treturn true;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t// 회원가입 기능\r\n");
      out.write("\t\t\tfunction signValidate(){\r\n");
      out.write("\t\t\t\tif($(\"#signupId\").val().trim().length<=3){\r\n");
      out.write("\t\t\t\t\talert(\"아이디를 4자 이상입력하세요\");\r\n");
      out.write("\t\t\t\t\t$(\"#signupId\").focus();\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\treturn false;\t// return값이 false면 submit이 되지 않는다.\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif(!$(\"#signupId\").is(\"readonly\")){\r\n");
      out.write("\t\t\t\t\talert(\"아이디 중복검사를 해주세요\");\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif($(\"#signupPwd\").val().trim().length<=3){\r\n");
      out.write("\t\t\t\t\talert(\"비밀번호를 입력하세요\");\r\n");
      out.write("\t\t\t\t\t$(\"#signupPwd\").focus();\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\treturn true;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 로그인을 안했을 시 MyPage를 누르면 로그인창이 열림\r\n");
      out.write("\t\t\t$(\"#MyPage\").click(function(){\r\n");
      out.write("\t\t\t\t$(\"#loginBtn\").click();\r\n");
      out.write("\t\t\t\t$(\"#menu\").removeClass(\"open\");\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 로그인, 회원가입중 하나가 열려 있을 시 발동 (다른 모달 및 메뉴바를 없앤다.)\r\n");
      out.write("\t\t\t$(\"#loginBtn\").click(function(){\r\n");
      out.write("\t\t\t\tif($(\"#menu\").hasClass(\"open\")){\r\n");
      out.write("\t\t\t\t\t$(\"#menu\").removeClass(\"open\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif($(\"#signupModal\").hasClass(\"show\")){\r\n");
      out.write("\t\t\t\t\t$(\"#signupModal\").modal('hide');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#signupBtn\").click(function(){\r\n");
      out.write("\t\t\t\tif($(\"#menu\").hasClass(\"open\")){\r\n");
      out.write("\t\t\t\t\t$(\"#menu\").removeClass(\"open\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif($(\"#loginModal\").hasClass(\"show\")){\r\n");
      out.write("\t\t\t\t\t$(\"#loginModal\").modal('hide');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#matchingPwd\").hide();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 아이디 중복 체크\r\n");
      out.write("\t\tfunction idCheck(){\r\n");
      out.write("\t\t\tvar checkid = $(\"#signupId\").val();\r\n");
      out.write("\t\t\tconsole.log(checkid);\r\n");
      out.write("\t\t\tif(checkid == \"\" || checkid.length <4){\r\n");
      out.write("\t\t\t\talert(\"아이디를 4글자 이상으로 적어주세요\");\t\t\t\t\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl : \"/Semi_LF/checkid.me\",\r\n");
      out.write("\t\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\t\tdata : {checkid : checkid},\r\n");
      out.write("\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\tif(data == 1){\r\n");
      out.write("\t\t\t\t\t\t\talert(\"이미 사용중인 아이디입니다.\");\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#signupId\").val(\"\");\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#signupId\").focus();\r\n");
      out.write("\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\talert(\"사용 가능한 아이디입니다.\");\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#signupId\").attr(\"readonly\", \"true\");\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 비밀번호 일치 기능\r\n");
      out.write("\t\t$(\"#signupPwd2\").keyup(function(){\r\n");
      out.write("\t\t\tvar pwd1 = $(\"#signupPwd\").val();\r\n");
      out.write("\t\t\tvar pwd2 = $(\"#signupPwd2\").val();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(pwd1 != \"\" || pwd2 != \"\"){\r\n");
      out.write("                if(pwd1 == pwd2){\r\n");
      out.write("                    $(\"#matchingPwd\").text(\"비밀번호가 일치합니다.\").css(\"color\",\"blue\");\r\n");
      out.write("                    $(\"#matchingPwd\").show();\r\n");
      out.write("                }else{\r\n");
      out.write("                    $(\"#matchingPwd\").text(\"비밀번호가 일치하지 않습니다.\").css(\"color\",\"red\");;\r\n");
      out.write("                \t$(\"#matchingPwd\").show();\r\n");
      out.write("                }\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(pwd1<=3){\r\n");
      out.write("\t\t\t\t$(\"#matchingPwd\").text(\"비밀번호를 4자 이상으로 적어주세요\").css(\"color\",\"red\");;\r\n");
      out.write("            \t$(\"#matchingPwd\").show();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).click(function(event) { // 메뉴바를 제외한 부분 클릭시 메뉴바 닫힘\r\n");
      out.write("\t\t\t\tif (!($(\"#menu\").is(event.target)|| $(\"#menuBtn\").is(event.target)\r\n");
      out.write("\t\t\t\t\t|| $(\"#menu\").children().is(event.target) || $(\r\n");
      out.write("\t\t\t\t\t\t\"#childsBtn\").children().is(event.target))) {\r\n");
      out.write("\t\t\t\t\t\tif ($(\"#menu\").hasClass(\"open\")) { //class에 open이 없을 시 open클래스 추가 있을 시 삭제\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#menu\").removeClass(\"open\");\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#logoutBtn\").click(function(){\r\n");
      out.write("\t\t\tlocation.href = \"");
      out.print(request.getContextPath());
      out.write("/logout.me\";\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t//본 예제에서는 도로명 주소 표기 방식에 대한 법령에 따라, 내려오는 데이터를 조합하여 올바른 주소를 구성하는 방법을 설명합니다.\r\n");
      out.write("\t\tfunction addressFind() {\r\n");
      out.write("\t\t\tnew daum.Postcode(\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\toncomplete : function(data) {\r\n");
      out.write("\t\t\t\t\t\t\t// 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t// 도로명 주소의 노출 규칙에 따라 주소를 조합한다.\r\n");
      out.write("\t\t\t\t\t\t\t// 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.\r\n");
      out.write("\t\t\t\t\t\t\tvar fullRoadAddr = data.roadAddress; // 도로명 주소 변수\r\n");
      out.write("\t\t\t\t\t\t\tvar extraRoadAddr = ''; // 도로명 조합형 주소 변수\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t// 법정동명이 있을 경우 추가한다. (법정리는 제외)\r\n");
      out.write("\t\t\t\t\t\t\t// 법정동의 경우 마지막 문자가 \"동/로/가\"로 끝난다.\r\n");
      out.write("\t\t\t\t\t\t\tif (data.bname !== ''\r\n");
      out.write("\t\t\t\t\t\t\t\t\t&& /[동|로|가]$/g.test(data.bname)) {\r\n");
      out.write("\t\t\t\t\t\t\t\textraRoadAddr += data.bname;\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t// 건물명이 있고, 공동주택일 경우 추가한다.\r\n");
      out.write("\t\t\t\t\t\t\tif (data.buildingName !== ''\r\n");
      out.write("\t\t\t\t\t\t\t\t\t&& data.apartment === 'Y') {\r\n");
      out.write("\t\t\t\t\t\t\t\textraRoadAddr += (extraRoadAddr !== '' ? ', '\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ data.buildingName : data.buildingName);\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t// 도로명, 지번 조합형 주소가 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.\r\n");
      out.write("\t\t\t\t\t\t\tif (extraRoadAddr !== '') {\r\n");
      out.write("\t\t\t\t\t\t\t\textraRoadAddr = ' (' + extraRoadAddr + ')';\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t// 도로명, 지번 주소의 유무에 따라 해당 조합형 주소를 추가한다.\r\n");
      out.write("\t\t\t\t\t\t\tif (fullRoadAddr !== '') {\r\n");
      out.write("\t\t\t\t\t\t\t\tfullRoadAddr += extraRoadAddr;\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t// 우편번호와 주소 정보를 해당 필드에 넣는다.\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('address1').value = data.zonecode; //5자리 새우편번호 사용\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('address2').value = fullRoadAddr;\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}).open();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t<div class=\"headbanner\">\r\n");
      out.write("\t\t<div id=\"slideDiv\">\r\n");
      out.write("\t\t\t<ul id=\"vertical\">\r\n");
      out.write("\t\t\t\t<li data-thumb=\"");
      out.print(request.getContextPath() );
      out.write("/images/cherry.png\"\r\n");
      out.write("\t\t\t\t\tdata-src=\"");
      out.print(request.getContextPath() );
      out.write("/images/cherry.png\">\r\n");
      out.write("\t\t\t    <img src=\"");
      out.print(request.getContextPath() );
      out.write("/images/cherry.png\" />\r\n");
      out.write("\t\t\t  </li>\r\n");
      out.write("\t\t\t  <li data-thumb=\"");
      out.print(request.getContextPath() );
      out.write("/images/applemango.jpg\"\r\n");
      out.write("\t\t\t  \t\tdata-src=\"");
      out.print(request.getContextPath() );
      out.write("/images/applemango.jpg\">\r\n");
      out.write("\t\t\t    <img src=\"");
      out.print(request.getContextPath() );
      out.write("/images/applemango.jpg\" />\r\n");
      out.write("\t\t\t  </li>\r\n");
      out.write("\t\t\t  <li data-thumb=\"");
      out.print(request.getContextPath() );
      out.write("/images/apple.png\"\r\n");
      out.write("\t\t\t  \t\tdata-src=\"");
      out.print(request.getContextPath() );
      out.write("/images/apple.png\">\r\n");
      out.write("\t\t\t    <img src=\"");
      out.print(request.getContextPath() );
      out.write("/images/apple.png\" />\r\n");
      out.write("\t\t\t  </li>\r\n");
      out.write("\t\t\t  <li data-thumb=\"");
      out.print(request.getContextPath() );
      out.write("/images/grape.jpg\"\r\n");
      out.write("\t\t\t  \t\tdata-src=\"");
      out.print(request.getContextPath() );
      out.write("/images/grape.jpg\">\r\n");
      out.write("\t\t\t    <img src=\"");
      out.print(request.getContextPath() );
      out.write("/images/grape.jpg\" />\r\n");
      out.write("\t\t\t  </li>\r\n");
      out.write("\t\t\t  <li data-thumb=\"");
      out.print(request.getContextPath() );
      out.write("/images/orange.jpg\"\r\n");
      out.write("\t\t\t  \t\tdata-src=\"");
      out.print(request.getContextPath() );
      out.write("/images/orange.jpg\">\r\n");
      out.write("\t\t\t    <img src=\"");
      out.print(request.getContextPath() );
      out.write("/images/orange.jpg\" />\r\n");
      out.write("\t\t\t  </li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"secondMainDiv\">\r\n");
      out.write("\t\t<div id=\"newProduct\" style=\"position:relative\">\r\n");
      out.write("\t\t<div style=\"position:absolute; top:0px; left:0px;\">\r\n");
      out.write("\t\t<iframe width=\"1200px\" height=\"620px\" src=\"https://www.kamis.or.kr/customer/main/main.do\" align=\"top\"  scrolling=\"no\" frameborder=\"0\" ></iframe>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"reviewSlide\">\r\n");
      out.write("\t\t\t<ul id=\"reviewSlider\">\r\n");
      out.write("\t\t\t\t");
 for(int i=1; i<=5 ;i++) {
      out.write("\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card cardSize\" >\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-header\" id=\"mReview");
      out.print(i);
      out.write("\">평점</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-body\" id=\"reContent");
      out.print(i);
      out.write("\">Content</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\tverticalSlider();\r\n");
      out.write("\t\treviewSliderFn();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tfunction verticalSlider(){\r\n");
      out.write("\t\t$(\"#vertical\").lightSlider({\r\n");
      out.write("\t\t\tgallery:true,\r\n");
      out.write("\t\t\titem:1,\r\n");
      out.write("\t\t\tloop:true,\r\n");
      out.write("\t\t\tvertical:true,\r\n");
      out.write("\t\t\tverticalHeight:450,\r\n");
      out.write("\t\t\tvThumbWidth:150,\r\n");
      out.write("\t\t\tthumbItem:4,\r\n");
      out.write("\t\t\tthumbMargin:4,\r\n");
      out.write("\t\t\tenableDrag: false,\r\n");
      out.write("\t\t\tauto : true, // 자동 슬라이드\r\n");
      out.write("\t\t\tspeed : 2000, // 슬라이드 되는 속도\r\n");
      out.write("\t\t\tpause : 5000,\r\n");
      out.write("\t\t\tslideMargin:0\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction reviewSliderFn(){\r\n");
      out.write("\t\t$(\"#reviewSlider\").lightSlider({\r\n");
      out.write("\t\t\titem:3,\r\n");
      out.write("\t\t\tmode:'slide',\r\n");
      out.write("\t\t\tloop:true,\r\n");
      out.write("\t\t\tenableDrag: false,\r\n");
      out.write("\t\t\tauto : true, // 자동 슬라이드\r\n");
      out.write("\t\t\tspeed : 2000, // 슬라이드 되는 속도\r\n");
      out.write("\t\t\tpause : 5000,\r\n");
      out.write("\t\t\tslideMargin:0\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t/* mTimer = setInterval(function() {\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl:\"/Semi_LF/mReview.me\"\r\n");
      out.write("\t\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t\tif(data.length == 0){\r\n");
      out.write("\t\t\t\t\t\tvar i = 1;\r\n");
      out.write("\t\t\t\t\t\tfor(var key in data){\r\n");
      out.write("\t\t\t\t\t\t\tvar grade = $(\"#mReview\"+i).html(\"\");\r\n");
      out.write("\t\t\t\t\t\t\tvar content = $(\"#reContent\"+i).html(\"\");\r\n");
      out.write("\t\t\t\t\t\t\tgrade.html(data[key].grade);\r\n");
      out.write("\t\t\t\t\t\t\tcontent.html(data[key].reContent);\r\n");
      out.write("\t\t\t\t\t\t\ti = i+1;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}, 30000); */\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
