/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.45
 * Generated at: 2019-10-28 15:29:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.Board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class PaymentView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>난 혼자 산다 결제</title>\r\n");
      out.write("<script src = \"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("   #searchBtn, #listBtn, #couponBtn, #paysubmit{\r\n");
      out.write("      background:  rgb(160, 200, 220);\r\n");
      out.write("      color: white;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("    #paysubmit{\r\n");
      out.write("        width: 150px;\r\n");
      out.write("        height: 40px;\r\n");
      out.write("    }\r\n");
      out.write("   \r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("      function paygo(){\r\n");
      out.write("          window.name = \"Payment\";\r\n");
      out.write("          // window.open(\"open할 window\", \"자식창 이름\", \"팝업창 옵션\");\r\n");
      out.write("          openWin = window.open(\"PaymentTest.jsp\",\r\n");
      out.write("                  \"PaymentA\", \"width=850, height=700, resizable = no, scrollbars = no\");\r\n");
      out.write("          }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    function sample6_execDaumPostcode() {\r\n");
      out.write("        new daum.Postcode({\r\n");
      out.write("            oncomplete: function(data) {\r\n");
      out.write("                // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.\r\n");
      out.write("\r\n");
      out.write("                // 각 주소의 노출 규칙에 따라 주소를 조합한다.\r\n");
      out.write("                // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.\r\n");
      out.write("                var addr = ''; // 주소 변수\r\n");
      out.write("                var extraAddr = ''; // 참고항목 변수\r\n");
      out.write("\r\n");
      out.write("                //사용자가 선택한 주소 타입에 따라 해당 주소 값을 가져온다.\r\n");
      out.write("                if (data.userSelectedType === 'R') { // 사용자가 도로명 주소를 선택했을 경우\r\n");
      out.write("                    addr = data.roadAddress;\r\n");
      out.write("                } else { // 사용자가 지번 주소를 선택했을 경우(J)\r\n");
      out.write("                    addr = data.jibunAddress;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                // 사용자가 선택한 주소가 도로명 타입일때 참고항목을 조합한다.\r\n");
      out.write("                if(data.userSelectedType === 'R'){\r\n");
      out.write("                    // 법정동명이 있을 경우 추가한다. (법정리는 제외)\r\n");
      out.write("                    // 법정동의 경우 마지막 문자가 \"동/로/가\"로 끝난다.\r\n");
      out.write("                    if(data.bname !== '' && /[동|로|가]$/g.test(data.bname)){\r\n");
      out.write("                        extraAddr += data.bname;\r\n");
      out.write("                    }\r\n");
      out.write("                    // 건물명이 있고, 공동주택일 경우 추가한다.\r\n");
      out.write("                    if(data.buildingName !== '' && data.apartment === 'Y'){\r\n");
      out.write("                        extraAddr += (extraAddr !== '' ? ', ' + data.buildingName : data.buildingName);\r\n");
      out.write("                    }\r\n");
      out.write("                    // 표시할 참고항목이 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.\r\n");
      out.write("                    if(extraAddr !== ''){\r\n");
      out.write("                        extraAddr = ' (' + extraAddr + ')';\r\n");
      out.write("                    }\r\n");
      out.write("                    // 조합된 참고항목을 해당 필드에 넣는다.\r\n");
      out.write("                    document.getElementById(\"sample6_extraAddress\").value = extraAddr;\r\n");
      out.write("                \r\n");
      out.write("                } else {\r\n");
      out.write("                    document.getElementById(\"sample6_extraAddress\").value = '';\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                // 우편번호와 주소 정보를 해당 필드에 넣는다.\r\n");
      out.write("                document.getElementById('sample6_postcode').value = data.zonecode;\r\n");
      out.write("                document.getElementById(\"sample6_address\").value = addr;\r\n");
      out.write("                // 커서를 상세주소 필드로 이동한다.\r\n");
      out.write("                document.getElementById(\"sample6_detailAddress\").focus();\r\n");
      out.write("            }\r\n");
      out.write("        }).open();\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <script>\r\n");
      out.write("   function same2m_info(f){\r\n");
      out.write("   f.name.value = f.o_name.value;\r\n");
      out.write("   f.phone.value = f.o_phone.value;\r\n");
      out.write("   }\r\n");
      out.write("   </script>\r\n");
      out.write("   \r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("   <br>\r\n");
      out.write("   <form name=\"order_form\">\r\n");
      out.write("    <fieldset>\r\n");
      out.write("    \r\n");
      out.write("   <h2>&nbsp;&nbsp;&nbsp;&nbsp;<img src=\"/SemiProject/images/wallet.png\" width=\"50px\" height=\"50px\">&nbsp;&nbsp;주문/결제\r\n");
      out.write("   <legend align=\"right\"><img src=\"/SemiProject/images/one.png\" width=\"30px\" height=\"30px\"> 장바구니 <img src=\"/SemiProject/images/point.png\" width=\"20px\" height=\"20px\"> <img src=\"/SemiProject/images/two.png\" width=\"30px\" height=\"30px\"> 주문/결제  <img src=\"/SemiProject/images/point.png\" width=\"20px\" height=\"20px\"> <img src=\"/SemiProject/images/three.png\" width=\"30px\" height=\"30px\"> 주문완료  &nbsp;&nbsp;&nbsp;</h2></legend>\r\n");
      out.write("    <hr><br>\r\n");
      out.write("   <fieldset>\r\n");
      out.write("   <h3>주문상품내역</h3>\r\n");
      out.write("   <img src=\"/SemiProject/images/320.jpg\" width=\"150px\" height=\"150px\">\r\n");
      out.write("   <br><br>\r\n");
      out.write("   </fieldset>\r\n");
      out.write("   <br><br>\r\n");
      out.write("   <h3>&nbsp;주문자 정보</h3>\r\n");
      out.write("    <hr><br><br>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("   <tr class=\"tr\">\r\n");
      out.write("  <th>&nbsp;&nbsp;* 이름:&nbsp;&nbsp;&nbsp;</th>\r\n");
      out.write("    <td class=\"m_info\"><input type=\"text\" name=\"o_name\" size=\"20\" placeholder=\"name\" id = \"o_name\"></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <br><br>\r\n");
      out.write("  <tr class=\"tr\">\r\n");
      out.write("  <th>&nbsp;&nbsp;* 연락처:</th>\r\n");
      out.write("    <td class=\"m_info\"><input type=\"phone\" name=\"o_phone\" size=\"20\" placeholder=\"phone\" id = \"o_phone\"></td>\r\n");
      out.write("  </tr><br><br>\r\n");
      out.write("                <label>&nbsp;&nbsp;&nbsp;이메일 : </label><input type=\"email\" placeholder=\"e-mail\" id =\"Cemail\"><br><br>\r\n");
      out.write("            <br><br><br>\r\n");
      out.write("           \r\n");
      out.write("           <h3>&nbsp;배송정보</h3>\r\n");
      out.write("            <hr><br><br>&nbsp;\r\n");
      out.write("            <tr>\r\n");
      out.write("   <td colspan=\"2\"><input type=\"checkbox\" id=\"same\"><label for=\"same\">주문자 정보와 동일합니다.</label></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("            <br><br>\r\n");
      out.write("   <tr class=\"tr\">\r\n");
      out.write("    <th>&nbsp;&nbsp;* 받는분:</th>\r\n");
      out.write("    <td class=\"m_info\"><input type=\"text\" name=\"name\" size=\"20\" placeholder=\"name\" id = \"v_name\"></td>\r\n");
      out.write("  </tr><br><br>\r\n");
      out.write("  \r\n");
      out.write("  <tr class=\"tr\">\r\n");
      out.write("    <th>&nbsp;&nbsp;* 연락처:</th>\r\n");
      out.write("    <td class=\"m_info\"><input type=\"phone\" name=\"phone\" size=\"20\" placeholder=\"phone\" id = \"v_phone\"></td>\r\n");
      out.write("  </tr><br><br>\r\n");
      out.write("  \r\n");
      out.write("                <label>&nbsp;&nbsp;* 우편번호 : <input type=\"text\" id=\"sample6_postcode\" placeholder=\"우편번호\">\r\n");
      out.write("<input type=\"button\" id = \"searchBtn\" onclick=\"sample6_execDaumPostcode()\" value=\"우편번호 찾기\"><br><br>\r\n");
      out.write("&nbsp;&nbsp;&nbsp;<input type=\"text\" id=\"sample6_address\" placeholder=\"주소\"><br>\r\n");
      out.write("&nbsp;&nbsp;&nbsp;<input type=\"text\" id=\"sample6_extraAddress\" placeholder=\"참고항목\">\r\n");
      out.write("            <input type=\"text\" id=\"sample6_detailAddress\" placeholder=\"상세주소\">\r\n");
      out.write("            <br><br><br><label>&nbsp;&nbsp;&nbsp;배송시 요구사항:&nbsp;\r\n");
      out.write("       \r\n");
      out.write("            <script>\r\n");
      out.write("               $(function(){\r\n");
      out.write("                     //직접입력 인풋박스 기존에는 숨어있다가\r\n");
      out.write("                  $(\"#selboxDirect\").hide();\r\n");
      out.write("                  $(\"#selbox\").change(function() {\r\n");
      out.write("                               //직접입력을 누를 때 나타남\r\n");
      out.write("                     if($(\"#selbox\").val() == \"direct\") {\r\n");
      out.write("                        $(\"#selboxDirect\").show();\r\n");
      out.write("                     }  else {\r\n");
      out.write("                        $(\"#selboxDirect\").hide();\r\n");
      out.write("                     }\r\n");
      out.write("                  });\r\n");
      out.write("               });\r\n");
      out.write("            </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<select id=\"selbox\" name=\"selbox\" style=\"height:21.33px;\">\r\n");
      out.write("                                <option value=\"배송 전 연락 바랍니다.\">배송 전 연락 바랍니다.</option>\r\n");
      out.write("                        <option value=\"문 앞에 놓아주세요\">문 앞에 놓아주세요.</option>\r\n");
      out.write("                        <option value=\"부재시 택배함에 넣어주세요\">부재시 택배함에 넣어주세요.</option>\r\n");
      out.write("                        <option value=\"direct\">직접 입력</option>\r\n");
      out.write("                        <option value=\"없음\">없음</option>\r\n");
      out.write("                     </select>\r\n");
      out.write("                     <br><br>\r\n");
      out.write("                     &nbsp;&nbsp;<input type=\"text\" id=\"selboxDirect\" name=\"selboxDirect\" style=\"width: 300px;\" placeholder=\"이곳에 입력해주세요\">\r\n");
      out.write("            <br><br>\r\n");
      out.write("            &nbsp;&nbsp;&nbsp;<input type = \"submit\" id= \"listBtn\" value = \"배송지 목록\"></label><br><br><br><br><br>\r\n");
      out.write("           \r\n");
      out.write("           ");
      out.write("\r\n");
      out.write("            <h3>&nbsp;난 혼자 산다 포인트</h3>\r\n");
      out.write("            <hr><br>\r\n");
      out.write("            <h4>&nbsp;&nbsp;&nbsp;포인트&nbsp;&nbsp;</label><input type=\"text\" id = \"point\">&nbsp;P</h4>\r\n");
      out.write("            &nbsp;&nbsp;&nbsp;사용 가능 포인트: &nbsp; ");
      out.write("P &nbsp;&nbsp;\r\n");
      out.write("            <input type=\"checkbox\" name=\"allpoint\" id=\"allpoint\"><label for=\"allpoint\">전액사용</label>\r\n");
      out.write("           <br><br><br><br>\r\n");
      out.write("            <h4>&nbsp;&nbsp; 예상 적립 포인트: &nbsp; XXX 적립 예정</h4>\r\n");
      out.write("          \r\n");
      out.write("            &nbsp;&nbsp; * 일반 등급은 2% 적립, VIP등급은 5% 적립\r\n");
      out.write("            <br><br><br><br><br>\r\n");
      out.write("          ");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            <h3>&nbsp;최종 결제금액</h3>\r\n");
      out.write("             <hr><br><br>\r\n");
      out.write("             &nbsp;&nbsp;주문금액 <div id = \"orderpay\">");
      out.write("</div>원\r\n");
      out.write("             <br><br>\r\n");
      out.write("             &nbsp;&nbsp;배송비");
      out.write("\r\n");
      out.write("            ");
      out.write("\r\n");
      out.write("             0원\r\n");
      out.write("             ");
      out.write("\r\n");
      out.write("             <br><br>\r\n");
      out.write("             &nbsp;&nbsp;포인트 사용 <div id = \"usePoint\"></div>\r\n");
      out.write("             <br><br>\r\n");
      out.write("             \r\n");
      out.write("             <h3>&nbsp;&nbsp;총 결제금액</h3>\r\n");
      out.write("             <div id=\"allPay\"></div>\r\n");
      out.write("             \r\n");
      out.write("\r\n");
      out.write("             <br><br>\r\n");
      out.write("             <h3>&nbsp;결제 수단</h3>\r\n");
      out.write("             <hr><br><br><br>\r\n");
      out.write("             \r\n");
      out.write("               <div>\r\n");
      out.write("                  결제 수단 <br><br>\r\n");
      out.write("                  <a href=\"javascript:void(0);\" id=\"aaa\" style=\" display: inline-block; width: 150px; height: 40px; text-decoration:none; text-align: center;\">\r\n");
      out.write("                     <font size=\"3\">신용카드</font>\r\n");
      out.write("                  </a>\r\n");
      out.write("                  <a href=\"javascript:void(0);\" id=\"bbb\" style=\" display: inline-block; width: 150px; height: 40px; text-decoration:none; text-align: center;\">\r\n");
      out.write("                     <font size=\"3\">무통장입금</font>\r\n");
      out.write("                  </a>\r\n");
      out.write("                  <a href=\"javascript:void(0);\"  id=\"ccc\" style=\" display: inline-block; width: 150px; height: 40px; text-decoration:none; text-align: center;\">\r\n");
      out.write("                     <font size=\"3\">실시간 계좌이체</font>\r\n");
      out.write("                  </a>\r\n");
      out.write("                  <br>\r\n");
      out.write("                  <a href=\"javascript:void(0);\"  id=\"ddd\" style=\" display: inline-block; width: 150px; height: 40px; text-decoration:none; text-align: center;\">\r\n");
      out.write("                     <font size=\"3\">휴대폰결제</font>\r\n");
      out.write("                  </a>\r\n");
      out.write("                  <a href=\"javascript:void(0);\"  id=\"eee\" style=\" display: inline-block; width: 150px; height: 40px; text-decoration:none; text-align: center;\">\r\n");
      out.write("                     <font size=\"3\">삼성페이</font>\r\n");
      out.write("                  </a>\r\n");
      out.write("\r\n");
      out.write("               </div>\r\n");
      out.write("\r\n");
      out.write("            <script>\r\n");
      out.write("               $(document).ready(function() {\r\n");
      out.write("                  $(\"#aaa\").click(function() {\r\n");
      out.write("                     document.getElementById(\"throw\").value = 'card';\r\n");
      out.write("                  });\r\n");
      out.write("                  $(\"#bbb\").click(function() {\r\n");
      out.write("                     $(\"#infoarea\").hide();\r\n");
      out.write("                     document.getElementById(\"throw\").value = 'vbank';\r\n");
      out.write("                  });\r\n");
      out.write("                  $(\"#ccc\").click(function() {\r\n");
      out.write("                     $(\"#infoarea\").hide();\r\n");
      out.write("                     document.getElementById(\"throw\").value = 'trans';\r\n");
      out.write("                     return false;\r\n");
      out.write("                  });\r\n");
      out.write("                  $(\"#ddd\").click(function() {\r\n");
      out.write("                     $(\"#infoarea\").hide();\r\n");
      out.write("                     document.getElementById(\"throw\").value = 'phone';\r\n");
      out.write("                  });\r\n");
      out.write("                  $(\"#eee\").click(function() {\r\n");
      out.write("                     $(\"#infoarea\").hide();\r\n");
      out.write("                     document.getElementById(\"throw\").value = 'samsung';\r\n");
      out.write("                  });\r\n");
      out.write("                  \r\n");
      out.write("               });\r\n");
      out.write("            </script>\r\n");
      out.write("                <br><br><br>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            <input type=\"hidden\" id=\"throw\" >\r\n");
      out.write("            <input id=\"paysubmit\" type=\"button\" value=\"결제하기\" onclick=\"paygo()\">\r\n");
      out.write("                        \r\n");
      out.write("               \r\n");
      out.write("               \r\n");
      out.write("   <script>\r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("   $(function() {\r\n");
      out.write("\r\n");
      out.write("            $(\"#same\").change(function(){ \r\n");
      out.write("              if($(\"#same\").is(\":checked\")){\r\n");
      out.write("                 $(\"input[name=name]\").val($(\"input[name=o_name]\").val());\r\n");
      out.write("                 $(\"input[name=phone]\").val($(\"input[name=o_phone]\").val());\r\n");
      out.write("              } else{\r\n");
      out.write("                 $(\"input[name=name]\").val(\"\");\r\n");
      out.write("                 $(\"input[name=phone]\").val(\"\");\r\n");
      out.write("              }\r\n");
      out.write("            });\r\n");
      out.write("      \r\n");
      out.write("      $(\"#allpoint\").change(function() {\r\n");
      out.write("\r\n");
      out.write("         if ($(\"#allpoint\").is(\":checked\")) {\r\n");
      out.write("            $(\"#point\").val(");
      out.write(");\r\n");
      out.write("            $(\"#usePoint\").html($(\"#point\").val());\r\n");
      out.write("            allPay($(\"#point\").val());\r\n");
      out.write("            $(\"#point\").attr(\"disabled\", true);\r\n");
      out.write("         }else{\r\n");
      out.write("            $(\"#point\").attr(\"disabled\", false);\r\n");
      out.write("            $(\"#usePoint\").html(0);\r\n");
      out.write("             allPay(0);\r\n");
      out.write("            $(\"#point\").val(\"\");\r\n");
      out.write("         }\r\n");
      out.write("      });\r\n");
      out.write("      \r\n");
      out.write("      $(\"#point\").keyup(function(){\r\n");
      out.write("         if($(\"#point\").val().length == 0){\r\n");
      out.write("            $(\"#usePoint\").html(0);\r\n");
      out.write("            allPay(0);\r\n");
      out.write("         }else{\r\n");
      out.write("         \r\n");
      out.write("          $(\"#usePoint\").html($(\"#point\").val());\r\n");
      out.write("          allPay($(\"#point\").val());\r\n");
      out.write("          \r\n");
      out.write("         if(!/^[0-9]*$/.test($(\"#point\").val())){\r\n");
      out.write("            alert(\"숫자만 입력해주세요.\")\r\n");
      out.write("            $(\"#point\").val(\"\");\r\n");
      out.write("            $(\"#usePoint\").html(0);\r\n");
      out.write("             allPay(0);\r\n");
      out.write("         }else if($(\"#point\").val() > ");
      out.write("){\r\n");
      out.write("            alert(\"보유하고 있는 포인트가 적습니다.\");\r\n");
      out.write("            $(\"#point\").val(\"\");\r\n");
      out.write("            $(\"#usePoint\").html(0);\r\n");
      out.write("             allPay(0);\r\n");
      out.write("         }\r\n");
      out.write("         }\r\n");
      out.write("      });\r\n");
      out.write("      \r\n");
      out.write("   });\r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("   function allPay(point1){\r\n");
      out.write("      var point = parseInt(point1);\r\n");
      out.write("      var orderpay = ");
      out.write(";\r\n");
      out.write("      var dFee = ");
      out.write(";\r\n");
      out.write("      \r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("            </fieldset>\r\n");
      out.write("            </form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
