


CREATE OR REPLACE VIEW AdminINFO
AS
SELECT C.CID, USERID, USERPWD, ADDRESS, PHONE, EMAIL, JOINDATE, MODIFYDATE, STATUS, A.AID, A.ADMIN_LEVEL
FROM CUSTOMER C
JOIN ADMIN A ON(C.CID = A.CID)
WHERE STATUS = 'Y';

CREATE OR REPLACE VIEW SellerINFO
AS
SELECT C.CID, USERID, USERPWD, ADDRESS, PHONE, EMAIL, JOINDATE, MODIFYDATE, STATUS, S.SID, S.BSTATUS
FROM CUSTOMER C
JOIN SELLER S ON(C.CID = S.CID)
WHERE STATUS = 'Y';

COMMIT;

select * from AdminInfo;
select * from sellerInfo;
