--판매자 리뷰 확인용
CREATE OR REPLACE VIEW SELRV
AS
SELECT OL.SALE_DATE, OL.PNAME, OL.SCOUNT, OL.DANAME, 
OL.DAMESSAGE, OL.PID, OL.SID,
R.REID, R.RECONTENT, R.GRADE, R.REVIEW_DATE, R.REVIEW_MODIFY, R.STATUS, R.CID, R.SALE_ID 
FROM ORDERLIST OL, REVIEW R 
WHERE R.SALE_ID = OL.SALE_ID 
ORDER BY R.REID DESC;


--판매자 판매글 리스트 보는 용도
CREATE OR REPLACE VIEW PLODING
AS
SELECT ROWNUM RW, P.* FROM PLIST P ORDER BY PID DESC;