/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.45
 * Generated at: 2019-10-24 19:09:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.seller;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import LF.member.model.vo.*;
import java.sql.*;

public final class acpopup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("LF.member.model.vo");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"http://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<!-- <style>\r\n");
      out.write("\t.outer{\r\n");
      out.write("\tposition:absolute;\r\n");
      out.write("\tz-index:1600;\r\n");
      out.write("\t}\r\n");
      out.write("</style> -->\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"outer\">\r\n");
      out.write("\t<h1>사업자 정보 변경</h1>\r\n");
      out.write("\t<form id=\"updateForm\" action=\"");
      out.print(request.getContextPath() );
      out.write("/sellerUpdate.selr\" method=\"post\">\r\n");
      out.write("\t\t<table border:1px gray solid>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"200px\">입금계좌 은행명</td>\r\n");
      out.write("\t\t\t\t<td><select id=\"bName\" name=\"bName\" >\r\n");
      out.write("\t\t\t\t\t\t<option value=\"\">----</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"sh\">신한은행</option>\t\t<!-- 11,2자리 -->\r\n");
      out.write("\t\t\t\t\t\t<option value=\"nh\">농협은행</option>\t\t<!-- 11,2자리 -->\r\n");
      out.write("\t\t\t\t\t\t<option value=\"nhLocal\">지역농협</option>\t<!-- 13,4자리 -->\r\n");
      out.write("\t\t\t\t\t\t<option value=\"kb\">국민은행</option>\t\t<!-- 14자리 -->\r\n");
      out.write("\t\t\t\t\t\t<option value=\"wr\">우리은행</option>\t\t<!-- 13자리 -->\r\n");
      out.write("\t\t\t\t\t\t<option value=\"ibk\">기업은행</option>\t\t<!-- 14자리 -->\r\n");
      out.write("\t\t\t\t\t\t<option value=\"keb\">하나은행</option>\t\t<!-- 14자리 -->\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"200px\">입금계좌 계좌번호</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" maxlength=\"14\" id=\"acN\" name=\"acN\" required></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"200px\">예금주</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" maxlength=\"13\" id=\"acNa\" name=\"acNa\" required></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"sid\" name=\"sid\" value=\" \">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<p id=\"demo\"></p>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<div class=\"btns\" align=\"center\">\r\n");
      out.write("\t\t\t<button type=\"button\" id=\"maintain\" onclick=\"clean();\">값 불러오기</button>\r\n");
      out.write("\t\t\t<button id=\"change\" onclick=\"account();\">변경하기</button>\t\r\n");
      out.write("\t\t\t<!-- SellerInfoUpdate -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction clean(){\r\n");
      out.write("\t\t\t$(\"#acN\").empty();\r\n");
      out.write("\t\t\t$(\"#acNa\").empty();\r\n");
      out.write("\t\t\tvar bName = $(\"#bankName\", opener.document).val();\r\n");
      out.write("\t\t\tvar acNum = $(\"#acNum\", opener.document).val();\r\n");
      out.write("\t\t\tvar acName = $(\"#acName\", opener.document).val();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tconsole.log(bName);\r\n");
      out.write("\t\t\tconsole.log(acNum);\r\n");
      out.write("\t\t\tconsole.log(acName);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#bName\").val(bName).prop(\"selected\", true);\r\n");
      out.write("\t\t\t$(\"#acN\").val(acNum);\r\n");
      out.write("\t\t\t$(\"#acNa\").val(acName);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//은행 선택 여부\r\n");
      out.write("\t\tfunction account(){\r\n");
      out.write("\t\t\t//sid값 보내기\r\n");
      out.write("\t\t\tvar sid = $(\"#sid\", opener.document).val();\r\n");
      out.write("\t\t\tconsole.log(sid);\r\n");
      out.write("\t\t\t$(\"#sid\").val(sid);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//은행 선택 여부\r\n");
      out.write("\t\t\tvar bankName = $(\"#updateForm select[name='bName']\").val();\r\n");
      out.write("\t\t\talert(\"bName : \" + bankName);\r\n");
      out.write("\t\t\tconsole.log(bankName);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(bankName == \"\"){\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tconsole.log(true);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar acNum = $(\"#updateForm input[name='acN']\").val();\r\n");
      out.write("\t\t\t\tacNum = ((acNum+'').match(/\\d{1}/g));\r\n");
      out.write("\t\t\t\tconsole.log(acNum);\r\n");
      out.write("\t\t\t\tif(bankName == \"sh\" || bankName ==\"nh\"){\r\n");
      out.write("\t\t\t\t\t if(acNum.length != 11 && acNum.length != 12){\r\n");
      out.write("\t\t\t\t\t\t\talert(\"계좌번호가 잘못되었습니다.\");\r\n");
      out.write("\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\tconsole.log(true);\r\n");
      out.write("\t\t\t\t\t\t\treturn true;\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}else if(bankName == \"nhLocal\"){\r\n");
      out.write("\t\t\t\t\tif(acNum.length != 13 && acNum.length != 14){\r\n");
      out.write("\t\t\t\t\t\talert(\"계좌번호가 잘못되었습니다.\");\r\n");
      out.write("\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\tconsole.log(true);alert(\"항목을 선택해주세요.\");\r\n");
      out.write("\t\t\t\t\t\treturn true;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}else if(bankName == \"wr\"){\r\n");
      out.write("\t\t\t\t\tif(acNum.length != 13){\r\n");
      out.write("\t\t\t\t\t\talert(\"계좌번호가 잘못되었습니다.\");\r\n");
      out.write("\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\tconsole.log(true);alert(\"항목을 선택해주세요.\");\r\n");
      out.write("\t\t\t\t\t\treturn true;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\tif(acNum.length != 14){\r\n");
      out.write("\t\t\t\t\t\talert(\"계좌번호가 잘못되었습니다.\");\r\n");
      out.write("\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\tconsole.log(true);alert(\"항목을 선택해주세요.\");\r\n");
      out.write("\t\t\t\t\t\treturn true;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//Seller + Pattachment에 각각 값 입력.\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
