/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.45
 * Generated at: 2019-10-23 20:20:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.seller;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import LF.member.model.vo.*;
import java.sql.*;
import LF.member.model.vo.*;
import LF.member.model.vo.*;

public final class SellerInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/seller/../seller/sellerMenubar.jsp", Long.valueOf(1571861668270L));
    _jspx_dependants.put("/views/seller/../seller/../common/menubar.jsp", Long.valueOf(1571733532895L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("LF.member.model.vo");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

/*	Seller s = (Seller)request.getAttribute("seller"); 
	//로그인 된 정보에서 Seller 계정 가져오기

 	String bName = s.getbName();
	String bNum = s.getbNum();
	String cpNum = s.getCpNum();
	
	//물품판매 권한 승인 여부에 따라 문구가 달라야 함
	String bStatus = s.getbStatus() != 'Y' ? "판매 권한 검토중입니다" : "승인 완료";
	
	String bankName = s.getBankName();
	String acNum = s.getAcName();
	String acName = s.getAcName();
	int fId = s.getfId();	//사업자 등록증 봐야 할 거 같다고 생각되면 파일 불러오는거 구현해야 함  */
	
	Seller s = new Seller();
	
	int sid = 18;
	String bName = "사업자명";
	String bNum = "사업자번호";
	String cpNum = "법인번호";
	String bStatus = "test";
	/* String bStatus = s.getbStatus() != 'Y' ? "판매 권한 검토중입니다" : "승인 완료"; */
	
	String bankName = "sh";
	String acNum = "계좌번호";
	String acName = "예금주";
	

      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- 사업자 인증이 완료된 경우에만 사업자 정보 확인 가능 -->\r\n");
      out.write("<!-- 사업자 정보 페이지는 사업자 등록정보만 확인 가능 -->\r\n");
      out.write("<!-- 전화번호, 이메일, 주소, 비밀번호, 비밀번호 확인 등의 계정 정보 수정은 마이페이지에서 수정 -->\r\n");
      out.write("<!-- 사업자 등록 진행상황(미신청, 대기, 완료), 사업자 등록번호, 판매승인여부,  -->\r\n");
      out.write("\t<h1>사업자 정보 확인</h1>\r\n");
      out.write("\t");
      out.write('\r');
      out.write('\n');
 
	//1. 로그인 된 유저 정보 가져와야 함.(loginUser)
	Customer customer = (Customer)session.getAttribute("loginUser");
	
	//2. 해당 유저가 판매자로 등록되어 있는지 확인해야 함. 등록되어 있으면 해당 값 가져옴 (seller)
	Seller seller = (Seller)session.getAttribute("sellerUser");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("\t#sellerMenu{\r\n");
      out.write("\t\tmargin-top : 130px;\r\n");
      out.write("\t\twidth: 200px; \r\n");
      out.write("\t\theight: 500px;\t\r\n");
      out.write("\t\tdisplay:inline-block;\r\n");
      out.write("\t\ttext-align:center;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write('\r');
      out.write('\n');

	Customer loginUser = (Customer)session.getAttribute("loginUser");
	Seller sellerUser = (Seller)session.getAttribute("sellerUser");
	Admin adminUser = (Admin)session.getAttribute("adminUser");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\"> \r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("\t.headerNavi{\r\n");
      out.write("\t\tdisplay:inline-block;\r\n");
      out.write("\t\tborder-radius:5px;\r\n");
      out.write("\t\twidth:auto;\r\n");
      out.write("\t\theight:auto;\r\n");
      out.write("\t}\r\n");
      out.write("\t#loginBtn{\r\n");
      out.write("\t\tbackground:url('");
      out.print(request.getContextPath());
      out.write("/images/login.png') no-repeat;\r\n");
      out.write("\t\tbackground-size: cover; \r\n");
      out.write("\t\tbackground-repeat: no-repeat; \r\n");
      out.write("\t\tbackground-position: center;\r\n");
      out.write("\t\tborder: 0px;\r\n");
      out.write("\t\theight: 75px;\r\n");
      out.write("\t\twidth : 100px;\r\n");
      out.write("\t}\r\n");
      out.write("\t#menuBtn{\r\n");
      out.write("\t\tbackground:url('");
      out.print(request.getContextPath());
      out.write("/images/menubtn.png') no-repeat;\r\n");
      out.write("\t\tbackground-size: 80%; \r\n");
      out.write("\t\tbackground-repeat: no-repeat; \r\n");
      out.write("\t\tbackground-position: center;\r\n");
      out.write("\t\tborder: 0px;\r\n");
      out.write("\t\theight: 75px;\r\n");
      out.write("\t\twidth : 75px;\r\n");
      out.write("\t}\r\n");
      out.write("\t#signUpBtn{\r\n");
      out.write("\t\tbackground:url('");
      out.print(request.getContextPath());
      out.write("/images/signup2.png') no-repeat;\r\n");
      out.write("\t\tbackground-size: cover; \r\n");
      out.write("\t\tbackground-position: center;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tborder: 0px;\r\n");
      out.write("\t\theight: 75px;\r\n");
      out.write("\t\twidth : 100px;\r\n");
      out.write("\t}\r\n");
      out.write("\t#logoutBtn{\r\n");
      out.write("\t\tbackground:url('");
      out.print(request.getContextPath());
      out.write("/images/login.png') no-repeat;\r\n");
      out.write("\t\tbackground-size: cover; \r\n");
      out.write("\t\tbackground-position: center;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tborder: 0px;\r\n");
      out.write("\t\theight: 75px;\r\n");
      out.write("\t\twidth : 100px;\r\n");
      out.write("\t}\r\n");
      out.write("\t#inlineUl li{\r\n");
      out.write("\t\tdisplay:inline;\r\n");
      out.write("\t}\r\n");
      out.write("\t#rightMenu{\r\n");
      out.write("\t\talign:right;\r\n");
      out.write("\t}\r\n");
      out.write("\t#menu{\r\n");
      out.write("\t\twidth: 200px; \r\n");
      out.write("\t\theight:calc(100% - 150px); \r\n");
      out.write("\t\tposition: fixed; \r\n");
      out.write("\t\ttop: 130px; \r\n");
      out.write("\t\tleft: -320px; \r\n");
      out.write("\t\tz-index: 1055; \r\n");
      out.write("\t\tborder: 1px solid red; \r\n");
      out.write("\t\tbackground-color: green; \r\n");
      out.write("\t\ttext-align: center; \r\n");
      out.write("\t\ttransition: All 0.2s ease;\r\n");
      out.write("\t\tpadding-left: 20px;\r\n");
      out.write("\t\tpadding-right: 20px;\r\n");
      out.write("\t\tpadding-top: 50px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#menu.open{\r\n");
      out.write("\t\tleft:0px;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- header역할을 하며 로그인, 회원가입, 메뉴바를 열수 있는 버튼을 생성 -->\r\n");
      out.write("\t<div class=\"navbar navbar-expand-sm bg-light navbar-dark fixed-top row\" style=\"min-width: 1200px; z-index:1055; float:top;\" >\r\n");
      out.write("\t\t<div class=\"headerNavi col-sm-1\" align=\"left\" >\r\n");
      out.write("\t\t\t<input id=\"menuBtn\" type=\"button\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"headerNavi col-sm-8\" align=\"center\">\r\n");
      out.write("\t\t\t<img id=\"logo\" src=\"");
      out.print(request.getContextPath());
      out.write("/images/logo.png\" height='75' width=\"300\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"headerNavi col-sm-3\" id=\"rightMenu\" >\r\n");
      out.write("\t\t\t");
 if(loginUser == null) {
      out.write("\r\n");
      out.write("\t\t\t\t<ul id=\"inlineUl\">\r\n");
      out.write("\t\t\t\t\t<li><button id=\"loginBtn\" type=\"button\" style=\"align:right;\" data-toggle=\"modal\" data-target=\"#loginDiv\"></button></li>\r\n");
      out.write("\t\t\t\t\t<li><button id=\"signUpBtn\" type=\"button\" style=\"align:right;\" data-toggle=\"modal\" data-target=\"#loginDiv\"></button></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t");
} else { 
      out.write("\r\n");
      out.write("\t\t\t\t<ul id=\"inlineUl\">\r\n");
      out.write("\t\t\t\t\t<li><p>");
      out.print(loginUser.getUserName() );
      out.write("님 환영합니다.</li>\r\n");
      out.write("\t\t\t\t\t<li><button id=\"logoutBtn\" type=\"button\" style=\"align:right;\"></button></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 슬라이드 형식으로 버튼 클릭시 도출되는 메뉴바 -->\r\n");
      out.write("\t<div id=\"menu\">\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t");
 if(loginUser == null || loginUser.getGroupNum().equals("1")) {
      out.write("\r\n");
      out.write("\t\t\t\t");
 if(loginUser == null) {
      out.write("\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-light\" id=\"subLoginBtn\">로그인</button>\r\n");
      out.write("\t\t\t\t");
} else {
      out.write("\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-light\" id=\"\">1</button>\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-light\" id=\"\"></button>\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-light\" id=\"\"></button>\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-light\" id=\"\"></button>\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-light\" id=\"\"></button>\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-light\" id=\"\"></button>\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-light\" id=\"\"></button>\r\n");
      out.write("\t\t\t");
} else if(loginUser.getGroupNum().equals("2")){
      out.write("\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-light\" id=\"\">2</button>\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-light\" id=\"\"></button>\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-light\" id=\"\"></button>\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-light\" id=\"\"></button>\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-light\" id=\"\"></button>\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-light\" id=\"\"></button>\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-light\" id=\"\"></button>\r\n");
      out.write("\t\t\t");
} else {
      out.write("\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-light\" id=\"adminPage\">관리자페이지</button>\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-light\" id=\"\"></button>\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-light\" id=\"\"></button>\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-light\" id=\"\"></button>\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-light\" id=\"\"></button>\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-light\" id=\"\"></button>\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-light\" id=\"\"></button>\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- var list = [\"Home\", \"마이페이지\", \"상품 게시판\", \"장바구니\", \"FAQ\", \"1:1 고객 문의\"];\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tvar list = [\"Home\", \"로그인\", \"상품 게시판\", \"장바구니\", \"FAQ\", \"1:1 고객 문의\"];\r\n");
      out.write("\t\t\t\tfor(var i=0; i<list.length; i++){\r\n");
      out.write("\t\t\t\t\tvar $btn = $(\"<button>\").css({\"width\":\"150px\", \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t \"height\": \"50px\", \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t \"margin\":\"10px\"});\r\n");
      out.write("\t\t\t\t\t$btn.attr(\"id\",\"before\"+i);\r\n");
      out.write("\t\t\t\t\t$btn.addClass(\"btn btn-light\");\r\n");
      out.write("\t\t\t\t\t$btn.html(list[i]);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$menuDiv.append($btn); -->\r\n");
      out.write("\t<!-- 로그인창 만들 div -->\r\n");
      out.write("\t");
 if(loginUser == null) {
      out.write("\r\n");
      out.write("\t<div id=\"loginDiv\" class=\"modal fade\" id=\"loginModal\" tabindex=\"-1\" role=\"dialog\">\r\n");
      out.write("\t\t<form id=\"loginForm\" action=\"");
      out.print(request.getContextPath());
      out.write("/login.me\"\r\n");
      out.write("\t\tonsubmit=\"return validate();\" method=\"post\">\r\n");
      out.write("\t\t<div class=\"modal-dialog modal-dialog-centered\" style=\"width: 400px;\">\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Modal Header -->\r\n");
      out.write("\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t<h4 class=\"modal-title\">로그인</h4>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Modal body -->\r\n");
      out.write("\t\t\t\t<div class=\"modal-body\" style=\"padding: 30px;\">\r\n");
      out.write("\t\t\t\t\t<!-- <form id=\"loginInfo\"> -->\r\n");
      out.write("\t\t\t\t\t\t<table class=\"table-borderless\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>아이디</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" id=\"loginId\" name=\"loginId\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>비밀번호</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"password\" id=\"loginPwd\" name=\"loginPwd\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=2 align=\"right\"><a href=\"#\">아이디/비밀번호 찾기</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("<!-- \t\t\t\t\t</form> -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Modal footer -->\r\n");
      out.write("\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t<button id=\"loginConnect\" type=\"submit\" class=\"btn btn-success\">로그인</button>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-success\" data-dismiss=\"modal\" id=\"closeLogin\">닫기</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\t/* 메뉴바 버튼 */\r\n");
      out.write("\t\t\t$(\"#menuBtn\").click(function() {\r\n");
      out.write("\t\t\t\tif ($(\"#menu\").hasClass(\"open\")) { //class에 open이 없을 시 open클래스 추가 있을 시 삭제\r\n");
      out.write("\t\t\t\t\t$(\"#menu\").removeClass(\"open\");\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$(\"#menu\").addClass(\"open\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t// 일반회원 버튼\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 판매자 버튼\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 관리자 버튼\r\n");
      out.write("\t\t\t$(\"#adminPage\").click(function(){\r\n");
      out.write("\t\t\t\tlocation.href=\"../admin/adminMainPage.jsp\"\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t/* 로그인 기능 */\r\n");
      out.write("\t\t\t// validate() 함수 작성하기(form태그가 submit되었을 때 실행 됨)\r\n");
      out.write("\t\t\tfunction validate(){\r\n");
      out.write("\t\t\t\tif($(\"#userId\").val().trim().length==0){\r\n");
      out.write("\t\t\t\t\talert(\"아이디를 입력하세요\");\r\n");
      out.write("\t\t\t\t\t$(\"#userId\").focus();\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\treturn false;\t// return값이 false면 submit이 되지 않는다.\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif($(\"#userPwd\").val().trim().length==0){\r\n");
      out.write("\t\t\t\t\talert(\"비밀번호를 입력하세요\");\r\n");
      out.write("\t\t\t\t\t$(\"#userPwd\").focus();\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\treturn true;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t/* $(\"#loginConnect\").click(function() {\r\n");
      out.write("\t\t\t\tvar id = $(\"#loginId\").val();\r\n");
      out.write("\t\t\t\tvar pwd = $(\"#loginPwd\").val();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl : \"/Semi_LF/login.me\",\r\n");
      out.write("\t\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\tuserId : id,\r\n");
      out.write("\t\t\t\t\t\tuserPwd : pwd\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\t$(\"#loginModal\").modal(\"hide\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}); */\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#subLoginBtn\").click(function(){\r\n");
      out.write("\t\t\t\t$(\"#loginBtn\").click();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(document).click(function(event) { // 메뉴바를 제외한 부분 클릭시 메뉴바 닫힘\r\n");
      out.write("\t\t\t\tif (!($(\"#menu\").is(event.target)|| $(\"#menuBtn\").is(event.target)\r\n");
      out.write("\t\t\t\t\t|| $(\"#menu\").children().is(event.target) || $(\r\n");
      out.write("\t\t\t\t\t\t\"#childsBtn\").children().is(event.target))) {\r\n");
      out.write("\t\t\t\t\t\tif ($(\"#menu\").hasClass(\"open\")) { //class에 open이 없을 시 open클래스 추가 있을 시 삭제\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#menu\").removeClass(\"open\");\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#logoutBtn\").click(function(){\r\n");
      out.write("\t\t\tlocation.href = \"");
      out.print(request.getContextPath());
      out.write("/logout.me\";\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"sellerMenu\">\r\n");
      out.write("\t");
if(seller == null) {
      out.write("\r\n");
      out.write("\t  <script>\r\n");
      out.write("\t  var regist = confirm(\"아직 판매자로 등록하지 않았습니다. 판매자 등록을 하시겠습니까?\");\r\n");
      out.write("\t  if( regist == true ){\r\n");
      out.write("\t      alert(\"확인선택!\");\r\n");
      out.write("\t      $(\"#sr\").get(0).click();\r\n");
      out.write("\t   }else{\r\n");
      out.write("\t\t   //취소 선택\r\n");
      out.write("\t      alert(\"메인 페이지로 이동합니다.\");\r\n");
      out.write("\t\t  window.location.replace(\"../../views/Main/MainPage.jsp\");\r\n");
      out.write("\t\t  \r\n");
      out.write("\t   }\r\n");
      out.write("\t  </script>\r\n");
      out.write("\t");
}else { 
      out.write("\r\n");
      out.write("\t\t<a href=\"../Main/MainPage.jsp\"><span>LFmall HomePage</span></a><br>\r\n");
      out.write("\t\t<a id=\"sr\" href=\"");
      out.print(request.getContextPath() );
      out.write("/sellerRegist.selr?\"><span>판매자 등록하기</span></a><br>\t<!-- SellerRegistServlet -->\r\n");
      out.write("\t\t<a href=\"");
      out.print(request.getContextPath() );
      out.write("/sellerInfoMng.selr?\"><span>판매자 정보 관리</span></a><br>\r\n");
      out.write("\t\t<a href=\"");
      out.print(request.getContextPath() );
      out.write("/selInfo.ad\"><span>판매 상품 관리</span></a><br>\r\n");
      out.write("\t\t<a href=\"");
      out.print(request.getContextPath() );
      out.write("/cReportInfo.ad\"><span>상품 리뷰 확인</span></a><br>\r\n");
      out.write("\t\t<a href=\"");
      out.print(request.getContextPath() );
      out.write("/sReportInfo.ad\"><span>주문 관리</span></a><br>\r\n");
      out.write("\t\t<a href=\"");
      out.print(request.getContextPath() );
      out.write("/selList.ad\"><span>매출 관리</span></a><br>\r\n");
      out.write("\t\r\n");
      out.write("\t");
} 
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t<div class=\"SellerInfoArea\">\r\n");
      out.write("\t<!-- memberJoinForm.jsp에 있는 table을 복사해서 쓰자 -->\r\n");
      out.write("\r\n");
      out.write("\t\t<form id = \"bChange\" >\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"150px\" align=\"left\">\t사업자명   </td>\r\n");
      out.write("\t\t\t\t<td> ");
      out.print(bName );
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"150px\">\t사업자 등록번호   </td>\r\n");
      out.write("\t\t\t\t<td> ");
      out.print(bNum );
      out.write(" </td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"150px\">\t법인 번호   </td>\r\n");
      out.write("\t\t\t\t<td> ");
      out.print(cpNum );
      out.write(" </td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t<table>\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"150px\">판매 권한 승인 여부   </td>\r\n");
      out.write("\t\t\t\t<td> ");
      out.print(bStatus );
      out.write(" </td>\r\n");
      out.write("\t\t\t\t<td style=\"width:200px\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"150px\">\t입금계좌  </td>\r\n");
      out.write("\t\t\t\t<td> ");
      out.print(bankName );
      out.write(' ');
      out.write('/');
      out.write(' ');
      out.print(acNum );
      out.write(' ');
      out.print(acName );
      out.write(" </td>\r\n");
      out.write("\t\t\t\t<td><button id=\"bankAccount\" onclick=\"acPopup();\">입금계좌 변경</button></td>\r\n");
      out.write("\t\t\t\t<td style=\"width:200px\"></td>\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"sid\" value=\"");
      out.print(sid );
      out.write("\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"bankName\" value=\"");
      out.print(bankName );
      out.write("\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"acNum\" value=\"");
      out.print(acNum );
      out.write("\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"acName\" value=\"");
      out.print(acName );
      out.write("\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"150px\">사업자등록증 :  </td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(acName );
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td style=\"width:200px\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<div class=\"btns\" align=\"center\">\r\n");
      out.write("\t\t\t\t<button id=\"goMain\" onclick=\"goMain();\">메인으로</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tfunction goMain(){\r\n");
      out.write("\t\t\tlocation.href=\"/LimitedF/index.jsp\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction acPopup(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar url = \"../../views/seller/acpopup.jsp\";\r\n");
      out.write("            var name = \"popup test\";\r\n");
      out.write("            var option = \"width = 500, height = 500, top = 100, left = 200, location = no\"\r\n");
      out.write("            winObj = window.open(url, name, option);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* \r\n");
      out.write("\t\t$(\"#bNameChange\").click(function(){\r\n");
      out.write("\t\t\tvar bName = prompt(\"변경할 사업자명 입력 : \");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl:\"/LimitedF/bnc.do\",\t\t//SellerBNCServlet\r\n");
      out.write("\t\t\t\tdata:{bName:bname},\r\n");
      out.write("\t\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t\twindow.alert(\"사업자명 변경 완료\");\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror:function(data){\r\n");
      out.write("\t\t\t\t\twindow.alert(\"에러\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}); \r\n");
      out.write("\t\t});*/\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
